### ISSUE TITLE
Changes in rustfmt

### ISSUE THREAD

**Issue by jnicklas** [kaj/rsass#11]
The latest version of `rustfmt` changes the default formatting of Rust code quite dramatically, personally I like the new defaults, but I guess it is a matter of taste. The PR I just submitted fails on Travis due to these changes. This leaves us with a few options:

1. Reformat everything to the new style
2. Keep the existing formatting and apply legacy config so we can use the new version of rustfmt but keep the old style
3. Keep the existing formatting and pin to an old version of rustfmt

@kaj which do you think is the best option?

**Comment by kaj** [comment]
Generally, I say it's a good idea to try to keep up with the Rust community when it comes to code standard.

I recently selected the third alternative for [another project](/kaj/ructe), but that was mainly because `rustfmt` seemed to be in the middle of some rather fast changes and I just wanted to ignore it until it stabilized.  Maybe that has happened now?

Even when reformatting to new style, it is of course possible to have a `rustfmt.toml` specifying some project-local preferences.  Preferences I'd like to keep is:

* Limit line length to 80 characters.
* Allow most constructs to be single-line if they fit within that limit (e.g. struct initializers, call chains, and even if statements).
* I strongly prefer "visual" rather than "block" indention for function calls and function-like macro invocations.

**Comment by jnicklas** [comment]
I'm not sure whether rustfmt has stabilized now, I think there are still a lot of discussions going on about the default style format, and these will probably make themselves into rustfmt eventually.

From what I've seen it looks like rustfmt is moving more towards "block" indentation, rather than "visual" indentation, but I'm not sure whether that's everywhere or only for some constructs.

I think pinning to an old version is sensible if we want to avoid the churn for now.
