### ISSUE TITLE
core_functions::math::log::base::one_fuzzy fails on i386

### ISSUE THREAD

**Issue by jonassmedegaard** [kaj/rsass#168]
Hi,

With release v0.27.0, the test core_functions::math::log::base::one_fuzzy fails on i386:
```
---- core_functions::math::log::base::one_fuzzy stdout ----
thread 'core_functions::math::log::base::one_fuzzy' panicked at 'assertion failed: `(left == right)`
  left: `"a {\n  b: 693085564849.9646;\n}\n"`,
 right: `"a {\n  b: 693085564849.9645;\n}\n"`', rsass/tests/spec/core_functions/math/log.rs:54:9
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.63.0/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.63.0/library/core/src/panicking.rs:142:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /usr/src/rustc-1.63.0/library/core/src/panicking.rs:181:5
   4: spec::core_functions::math::log::base::one_fuzzy
             at ./tests/spec/core_functions/math/log.rs:54:9
   5: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.63.0/library/core/src/ops/function.rs:248:5

```
[full build log](https://buildd.debian.org/status/fetch.php?pkg=rsass&arch=i386&ver=0.27.0-1&stamp=1674937771&raw=0)

**Comment by kaj** [comment]
Thanks for the report!

Hm.  This test is a bit silly, in that it expects all the least significant bit of a floating point approximation to be "correct".  I have another test in the suite (`core_functions::math::variables::min_number`) ignored because it fails for me for a similar reason.

Maybe I should try to submit a change to [sass-spec](https://github.com/sass/sass-spec) that adds some rounding to the numbers to make the tests more stable?

I could mark this test as `ignore` in the spec, but then I would have to do that again every time I update the test suite, which probably have a high risk of me forgetting it.  Could you disable the test in a patch in the package spec?  If so, I guess you'll at least get a notification if things changes so the patch doesn't apply any more ...

**Comment by jonassmedegaard** [comment]
Thanks for confirming that the test is not important.

What I have done for now is skip the test at build time - i.e. the
equivalent of this:

  cargo test -- --skip core_functions::math::log::base::one_fuzzy
