### ISSUE TITLE
API for inspecting parsed selectors

### ISSUE THREAD

**Issue by maxbrunsfeld** [kaj/rsass#32]
👋 Thanks for building this!

I'm using `rsass::parse_scss_file` to parse some SCSS code. I want to use the syntax tree to perform my own selector-matching.

The API suits my needs in a lot of ways, except that I cannot inspect the contents of a selector. I can iterate through the *parts* of the selector, but I cannot introspect the contents of the `SelectorPart` because its definition lives inside the `selectors` module, which is not public.

I'd like to be able to distinguish between tag names, attribute selectors, and operators like `>`. Would you be open to making the variants of the `SelectorPart` enum public, or alternatively, adding methods for distinguishing these things, and obtaining tag names and operator values?

**Comment by kaj** [comment]
Thank you!

Making the `SelectorPart` variants pub is ok for me.  I guess the main reason I haven't done it yet is that I don't want to guarantee more API stability than necessary, but the since the main version number is still zero I guess I don't really guarantee any such stability anyway.

One thing I'm not sure about is the fact that I have Descendant as a variant without contents, so a selector like `div p` will be parsed to `vec![Simple("div"), Descendant, Simple("p")]` and not something like `Descendant { parent: Simple("div"), element: Simple("p") }`.  Which may imply I'm not sure that a `Selector` should contain a `Vec<SelectorPart>` at all ...

Another thing to look out for is that the actual string parts inside a `SelectorPart` are `SassString`; they may contain interpolation, and an instance that is a `Simple` may actually be a more complex selector when properly evaluated.

But given those limitations, if you still think it would be usefull to have the alternatives pub, yes, I can do that.

**Comment by kaj** [comment]
There is a `fn eval_selectors` in `output_style.rs` that may also need to be pub for this to be usefull?  Maybe it should be converted to a method of either `Selectors` or `Scope`.

**Comment by maxbrunsfeld** [comment]
For my use case, I am fine with the flat sequence representation of a selector.

I also don’t happen to support string interpolation in my project (I’m basically using this parser as a CSS parser with support for the ‘&’ nesting operator, which I think is likely to be standardized at some point.

So basically, the raw contents of the enum are totally fine for me, but I can understand that you might not want to commit to that API. I also agree with your point about being pre 1.0 though.

**Comment by maxbrunsfeld** [comment]
Thanks!
