### ISSUE TITLE
Use raw string literals for sass-spec tests?

### ISSUE THREAD

**Issue by glebm** [kaj/rsass#50]
sass-spec tests are unreadable in the current form (due to all the `"\n"`).

Perhaps rsass should use raw string literals instead?

https://rahul-thakoor.github.io/rust-raw-string-literals/
https://doc.rust-lang.org/reference/tokens.html#raw-string-literals

**Comment by kaj** [comment]
Yes, that would be nice ...   But it seems raw `\r` (CR) characters isn't allowed in raw string literals and cannot be escaped.  Since some tests contains them that seems to be a stopper.

The current code just formats both then input and output with the rust `Debug` formatter, which does a good job of converting the strings to source code that the rust compiler will get back the original strings from.  Any other implementation would have to keep that property, and from a few experiments I did, that does not seem to be too simple.

If you (or anyone else) manages to update the test converter to something that reads nicer _and_ preserves the actual test strings, I'll be happy to consider that code.  Just beware that it might not be as easy as it sounds.

One possible way _might_ be to identify strings that can be used as raw strings and do that for them (which may be as simple as checking for `\r` characters), while keeping the current format for other strings?

**Comment by kaj** [comment]
Tests now look like this example.  Still a lot of backslashes, but at least the lines are now separate lines and not small parts of one extremely long line for each test.

https://github.com/kaj/rsass/blob/19c7671dbb9bbe37890471bbbf6613068de0dbbd/tests/basic/main.rs#L57-L74

I think this solves the problem.  Are you okwith that, @glebm ?

**Comment by kaj** [comment]
Yes, I think that fix is enough.
