### ISSUE TITLE
Panic on numbers that are too big or too precise

### ISSUE THREAD

**Issue by divergentdave** [kaj/rsass#74]
I found through fuzzing that values like `2000000000000000000000000000000000000` or `0.2000000000000000000000000000000000000` will result in a panic due to integer overflow in `decimal_integer()` or `decimal_decimals()`. This can be addressed by using checked multiplication and addition inside these functions, and adding a fallback parser that uses arbitrary precision integers (or floating point numbers).

**Comment by kaj** [comment]
Hi!  I see you went ahead and contributed a fix.  Thank you for that, but before doing a real review of it, I'd like to take a step back and consider the alternatives.  These are the ones I can think of:

1) Keep using `Rational<isize>`, but make sure there is a proper error for overflowing and round numbers with too many decimals.
2) Use `Rational<BigInt>` instead of 'Rational<isize>`.
3) Use `Rational<BigInt>` for numbers that needs it, but `Rational<isize>` for other numbers.
4) Use `f64` for all numbers.
5) Use [`bigdecimal`](https://crates.io/crates/bigdecimal) for all numbers.

Alternative  3 is the one you implemented in #75 , but it is also arguably the most complex, and I think it would add even more complexity in the long run, consider e.g. the result of arithmetic of two `Numeric` values, where the result _may_ need to be a `NumericBig` value.

Alternative 5 is tempting, but I guess it would fail horribly at some simple arithmetic like (10 / 6) * 3.

I'm not sure, but I think other sass implementations are actually using float point numbers, so alternative 4 may be good enough to be spec compliant.

I guess the performance cost is your reason to keep the `Rational<isize>` for small numbers?  But is the performance of the arithmetic itself really relevant here?  Maybe when it comes to some color functions, but maybe color values don't need to use the same kind of numbers as number values?

**Comment by connorskees** [comment]
For comparison, `grass` currently uses [option 3](https://github.com/connorskees/grass/blob/master/src/value/number/mod.rs#L20). Initially everything was stored as a `BigInt`, but by switching to a hybrid representation `grass` was able to improve performance by about 50%. With regard to overflow, [`grass` uses checked operations](https://github.com/connorskees/grass/blob/master/src/value/number/mod.rs#L330), which it has tests for [here](https://github.com/connorskees/grass/blob/master/tests/number.rs#L171).

**Comment by kaj** [comment]
Hi again!  Sorry for the radio silence on this.  After some consideration, I think you are right that option 3 is best.
